Repository citizenlabsgr/adopt-a-drain, pull requests merged in 2019-03, with the labels that each got.

#139 Uncomment code that requests user location
  app/assets/javascripts/main.js.erb
Labels: review

#127 Fix broken images and formatting in emails
  app/mailers/thing_mailer.rb
  app/views/thing_mailer/_email_footer.html.erb
  app/views/thing_mailer/_logo_header.html.erb
  app/views/thing_mailer/_signature.html.erb
  app/views/thing_mailer/_social_media.html.erb
  app/views/thing_mailer/first_adoption_confirmation.html.erb
  app/views/thing_mailer/second_adoption_confirmation.html.erb
  config/environments/development.rb
  config/initializers/preview_interceptors.rb
  test/mailers/previews/thing_mailer_preview.rb
  test/mailers/thing_mailer_test.rb
Labels: in progress

#138 Don't bounce adopted icons forever
  app/assets/javascripts/main.js.erb
Labels: question, review, status-in-progress

#153 Use a smaller dataset for review apps
  app.json
Labels: review

#146 Get devise key from ENV
  .env.development
  .env.test
  app.json
  config/initializers/devise.rb
Labels: review

#142 turn on satellite view
  app/assets/javascripts/main.js.erb
Labels: review

#141 Set url options to host name
  config/environments/staging.rb
Labels: review

#165 157 gitignore
  config/database.yml
Labels: review

#155 Automatically refresh my drains
  app/assets/javascripts/main.js.erb
  app/models/thing.rb
Labels: review

#137 Update acceptable drain names
  app/models/thing.rb
  lib/thing_importer.rb
Labels: Priority-1, in progress, status-in-progress

#168 WIP on Rspec Feature Testing
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  INSTALL.md
  app/assets/javascripts/main.js.erb
  spec/features/sign_up_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: review

#171 Update Terms of Use
  app/views/sidebar/_tos.html.haml
Labels: review

#174 Finishes Rspec configuration
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/features/sign_up_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: review

#170 Remove Home page feedback
  app/views/main/index.html.haml
Labels: Priority-1, review

#178 119 second adopt email
  INSTALL.md
  app/assets/images/logos/drain-cleaner.png
  app/mailers/thing_mailer.rb
  app/views/thing_mailer/_email_footer.html.erb
  app/views/thing_mailer/_logo_header.html.erb
  app/views/thing_mailer/second_adoption_confirmation.html.erb
  config/application.rb
  config/environments/development.rb
  test/mailers/thing_mailer_test.rb
Labels: review

#182 rails upgrade 4.2.11.1
  Gemfile
  Gemfile.lock
  spec/features/sign_up_spec.rb.xxx
Labels: Priority-1, review

#187 update test geocode test
  config/locales/en.yml
  test/controllers/main_controller_test.rb
Labels: review

#190 add geokit-rails gem update tests
  Gemfile
  Gemfile.lock
  config/initializers/geokit_config.rb
  test/controllers/addresses_controller_test.rb
  test/controllers/reminders_controller_test.rb
  test/controllers/things_controller_test.rb
Labels: review

#200 176 date adopted
  app/assets/javascripts/main.js.erb
  app/controllers/application_controller.rb
  app/controllers/things_controller.rb
  app/mailers/thing_mailer.rb
  config/database.yml
  config/environments/development.rb
  db/migrate/20190319120408_add_date_adopted_to_things.rb
  db/schema.rb
  test/controllers/info_window_controller_test.rb
  test/controllers/reminders_controller_test.rb
  test/controllers/things_controller_test.rb
Labels: review

#201 rename date_adopted to adopted_at
  .gitignore
  Procfile
  app/assets/javascripts/main.js.erb
  app/controllers/things_controller.rb
  db/migrate/20190321173533_rename_date_adopted_to_adopted_at_in_things.rb
  db/schema.rb
  docker-compose.yml
  release-tasks.sh
  test/controllers/info_window_controller_test.rb
  test/controllers/reminders_controller_test.rb
  test/controllers/things_controller_test.rb
Labels: review

#208 edit profile
  app/assets/javascripts/main.js.erb
  app/controllers/users_controller.rb
  app/views/sidebar/_combo_form.html.haml
  app/views/sidebar/_forgot_password.html.haml
  app/views/sidebar/_login_form.html.haml
  app/views/sidebar/_search.html.haml
  app/views/sidebar/_signup_form.html.haml
  app/views/sidebar/edit_profile.html.haml
  test/controllers/users_controller_test.rb
Labels: review

#209 set default name to Storm Drain
  lib/thing_importer.rb
  test/lib/thing_importer_test.rb
Labels: review

#213 updated email footer
  app/views/thing_mailer/_email_footer.html.erb
Labels: review
